package com.google.android.gms.internal.ads;

import android.content.Context;
import android.content.SharedPreferences;
import android.content.SharedPreferences.Editor;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;

@yh
public final class ra
{
  private static final ga<String> A;
  public static final ga<String> Aa;
  private static final ga<String> Ab;
  public static final ga<String> Ac;
  public static final ga<String> Ad;
  private static final ga<Boolean> Ae;
  public static final ga<Integer> B;
  public static final ga<String> Ba;
  private static final ga<Integer> Bb;
  public static final ga<Long> Bc;
  public static final ga<Integer> Bd;
  public static final ga<Boolean> Be;
  public static final ga<Integer> C;
  public static final ga<Boolean> Ca;
  private static final ga<Integer> Cb;
  public static final ga<Boolean> Cc;
  public static final ga<Boolean> Cd;
  private static final ga<Boolean> Ce;
  public static final ga<Integer> D;
  public static final ga<String> Da;
  private static final ga<Long> Db;
  private static final ga<Boolean> Dc;
  public static final ga<Boolean> Dd;
  public static final ga<Boolean> De;
  public static final ga<Long> E;
  public static final ga<Long> Ea;
  private static final ga<Long> Eb;
  private static final ga<Boolean> Ec;
  public static final ga<Long> Ed;
  public static final ga<Boolean> Ee;
  public static final ga<Long> F;
  public static final ga<Integer> Fa;
  private static final ga<Float> Fb;
  public static final ga<String> Fc;
  public static final ga<String> Fd;
  public static final ga<Boolean> Fe;
  public static final ga<Integer> G;
  public static final ga<Boolean> Ga;
  private static final ga<Float> Gb;
  private static final ga<String> Gc;
  public static final ga<String> Gd;
  public static final ga<Long> Ge;
  public static final ga<Boolean> H;
  public static final ga<Boolean> Ha;
  public static final ga<Boolean> Hb;
  private static final ga<String> Hc;
  public static final ga<String> Hd;
  public static final ga<String> He;
  public static final ga<String> I;
  public static final ga<Boolean> Ia;
  public static final ga<Boolean> Ib;
  public static final ga<String> Ic;
  public static final ga<String> Id;
  public static final ga<Integer> Ie;
  public static final ga<Long> J;
  public static final ga<Boolean> Ja;
  private static final ga<Integer> Jb;
  public static final ga<Integer> Jc;
  public static final ga<Integer> Jd;
  public static final ga<Integer> Je;
  public static final ga<Boolean> K;
  public static final ga<Boolean> Ka;
  public static final ga<String> Kb;
  private static final ga<Integer> Kc;
  public static final ga<Integer> Kd;
  public static final ga<Integer> Ke;
  public static final ga<Long> L;
  public static final ga<Boolean> La;
  public static final ga<String> Lb;
  public static final ga<Boolean> Lc;
  public static final ga<Boolean> Ld;
  public static final ga<Integer> Le;
  public static final ga<Boolean> M;
  public static final ga<Boolean> Ma;
  public static final ga<Boolean> Mb;
  public static final ga<String> Mc;
  public static final ga<Boolean> Md;
  private static final ga<Boolean> Me;
  public static final ga<Integer> N;
  private static final ga<Integer> Na;
  public static final ga<Boolean> Nb;
  private static final ga<Boolean> Nc;
  public static final ga<Boolean> Nd;
  private static final ga<Boolean> Ne;
  public static final ga<Long> O;
  private static final ga<String> Oa;
  public static final ga<Long> Ob;
  public static final ga<Boolean> Oc;
  public static final ga<Integer> Od;
  public static final ga<Boolean> Oe;
  public static final ga<Boolean> P;
  public static final ga<Boolean> Pa;
  public static final ga<Long> Pb;
  public static final ga<Boolean> Pc;
  public static final ga<Boolean> Pd;
  public static final ga<Boolean> Pe;
  public static final ga<Boolean> Q;
  public static final ga<Boolean> Qa;
  public static final ga<Boolean> Qb;
  public static final ga<Boolean> Qc;
  public static final ga<Boolean> Qd;
  public static final ga<Boolean> Qe;
  public static final ga<String> R;
  public static final ga<Boolean> Ra;
  public static final ga<Boolean> Rb;
  private static final ga<Boolean> Rc;
  private static final ga<Boolean> Rd;
  public static final ga<Integer> Re;
  public static final ga<Integer> S;
  public static final ga<Boolean> Sa;
  public static final ga<Long> Sb;
  public static final ga<Boolean> Sc;
  public static final ga<Boolean> Sd;
  public static final ga<Boolean> Se;
  private static final ga<Float> T;
  public static final ga<Boolean> Ta;
  private static final ga<Boolean> Tb;
  private static final ga<Boolean> Tc;
  public static final ga<String> Td;
  public static final ga<Integer> Te;
  private static final ga<String> U;
  private static final ga<Boolean> Ua;
  public static final ga<Boolean> Ub;
  private static final ga<String> Uc;
  public static final ga<String> Ud;
  private static final ga<Boolean> Ue;
  private static final ga<Boolean> V;
  public static final ga<Boolean> Va;
  private static final ga<Boolean> Vb;
  public static final ga<Long> Vc;
  public static final ga<Boolean> Vd;
  public static final ga<Boolean> Ve;
  private static final ga<Float> W;
  private static final ga<Boolean> Wa;
  private static final ga<Boolean> Wb;
  private static final ga<String> Wc;
  private static final ga<String> Wd;
  public static final ga<Integer> We;
  private static final ga<Boolean> X;
  public static final ga<Boolean> Xa;
  private static final ga<Boolean> Xb;
  private static final ga<Long> Xc;
  public static final ga<Integer> Xd;
  public static final ga<Boolean> Xe;
  private static final ga<Boolean> Y;
  private static final ga<String> Ya;
  public static final ga<Long> Yb;
  private static final ga<String> Yc;
  public static final ga<Boolean> Yd;
  public static final ga<Boolean> Ye;
  public static final ga<String> Z;
  private static final ga<Boolean> Za;
  public static final ga<Boolean> Zb;
  private static final ga<Boolean> Zc;
  public static final ga<Integer> Zd;
  public static final ga<Boolean> Ze;
  public static final ga<Boolean> _a;
  public static final ga<Boolean> _b;
  public static final ga<Boolean> _c;
  public static final ga<Boolean> _d;
  private static byte[] _e;
  private static final ga<String> a;
  public static final ga<String> aa;
  private static final ga<Long> ab;
  private static final ga<Long> ac;
  private static final ga<String> ad;
  private static final ga<Boolean> ae;
  public static final ga<String> b;
  public static final ga<String> ba;
  public static final ga<Boolean> bb;
  private static final ga<Long> bc;
  public static final ga<Boolean> bd;
  private static final ga<String> be;
  public static final ga<String> c;
  public static final ga<String> ca;
  public static final ga<Boolean> cb;
  public static final ga<Long> cc;
  public static final ga<Long> cd;
  private static final ga<Boolean> ce;
  public static final ga<String> d;
  public static final ga<Boolean> da;
  public static final ga<Long> db;
  public static final ga<Boolean> dc;
  private static final ga<String> dd;
  private static final ga<String> de;
  private static final ga<String> e;
  public static final ga<Boolean> ea;
  public static final ga<Long> eb;
  public static final ga<Long> ec;
  private static final ga<String> ed;
  private static final ga<Boolean> ee;
  private static final ga<Boolean> f;
  public static final ga<String> fa;
  public static final ga<Boolean> fb;
  public static final ga<Long> fc;
  private static final ga<String> fd;
  public static final ga<Boolean> fe;
  private static final ga<String> g;
  public static final ga<Boolean> ga;
  public static final ga<Long> gb;
  public static final ga<Boolean> gc;
  private static final ga<String> gd;
  public static final ga<String> ge;
  private static final ga<String> h;
  public static final ga<Boolean> ha;
  public static final ga<Boolean> hb;
  public static final ga<Boolean> hc;
  private static final ga<String> hd;
  private static final ga<Boolean> he;
  public static final ga<Boolean> i;
  public static final ga<Integer> ia;
  private static final ga<Boolean> ib;
  public static final ga<Long> ic;
  private static final ga<String> id;
  private static final ga<String> ie;
  private static final ga<Boolean> j;
  public static final ga<Integer> ja;
  public static final ga<Long> jb;
  public static final ga<Boolean> jc;
  private static final ga<Long> jd;
  public static final ga<Boolean> je;
  private static final ga<String> k;
  public static final ga<Integer> ka;
  public static final ga<Boolean> kb;
  public static final ga<Boolean> kc;
  public static final ga<Long> kd;
  public static final ga<Boolean> ke;
  public static final ga<Boolean> l;
  public static final ga<Integer> la;
  public static final ga<Boolean> lb;
  public static final ga<Boolean> lc;
  private static final ga<String> ld;
  private static final ga<Boolean> le;
  public static final ga<Boolean> m;
  public static final ga<Integer> ma;
  public static final ga<Boolean> mb;
  public static final ga<Boolean> mc;
  private static final ga<Long> md;
  public static final ga<Boolean> me;
  public static final ga<Boolean> n;
  public static final ga<Integer> na;
  public static final ga<Boolean> nb;
  public static final ga<Boolean> nc;
  public static final ga<Boolean> nd;
  public static final ga<Boolean> ne;
  public static final ga<String> o;
  public static final ga<Integer> oa;
  private static final ga<Boolean> ob;
  public static final ga<Boolean> oc;
  private static final ga<Integer> od;
  private static final ga<Boolean> oe;
  public static final ga<Float> p;
  public static final ga<Integer> pa;
  private static final ga<String> pb;
  public static final ga<Boolean> pc;
  private static final ga<Integer> pd;
  public static final ga<Boolean> pe;
  private static final ga<String> q;
  public static final ga<String> qa;
  private static final ga<Integer> qb;
  public static final ga<String> qc;
  private static final ga<Long> qd;
  public static final ga<Integer> qe;
  private static final ga<String> r;
  public static final ga<String> ra;
  private static final ga<Integer> rb;
  public static final ga<Boolean> rc;
  public static final ga<Boolean> rd;
  public static final ga<Boolean> re;
  private static final ga<Integer> s;
  public static final ga<Boolean> sa;
  public static final ga<Boolean> sb;
  public static final ga<Boolean> sc;
  public static final ga<Boolean> sd;
  public static final ga<Boolean> se;
  public static final ga<String> t;
  private static final ga<Boolean> ta;
  private static final ga<Boolean> tb;
  public static final ga<Boolean> tc;
  public static final ga<Boolean> td;
  public static final ga<Boolean> te;
  public static final ga<Integer> u;
  private static final ga<Long> ua;
  private static final ga<Boolean> ub;
  public static final ga<Boolean> uc;
  public static final ga<Long> ud;
  private static final ga<Boolean> ue;
  public static final ga<Integer> v;
  private static final ga<String> va;
  private static final ga<String> vb;
  public static final ga<Boolean> vc;
  public static final ga<Boolean> vd;
  public static final ga<Boolean> ve;
  public static final ga<Integer> w;
  public static final ga<Boolean> wa;
  private static final ga<String> wb;
  public static final ga<Boolean> wc;
  public static final ga<Boolean> wd;
  public static final ga<Boolean> we;
  public static final ga<Integer> x;
  public static final ga<Boolean> xa;
  private static final ga<Integer> xb;
  private static final ga<Boolean> xc;
  public static final ga<Long> xd;
  public static final ga<Boolean> xe;
  public static final ga<Integer> y;
  public static final ga<Boolean> ya;
  private static final ga<Integer> yb;
  private static final ga<Boolean> yc;
  public static final ga<Long> yd;
  public static final ga<Boolean> ye;
  public static final ga<Integer> z;
  public static final ga<Boolean> za;
  private static final ga<Integer> zb;
  private static final ga<String> zc;
  public static final ga<Boolean> zd;
  public static final ga<Boolean> ze;
  
  static
  {
    Boolean localBoolean1 = Boolean.valueOf(false);
    a = ga.a(0, "gads:sdk_core_experiment_id");
    b = ga.a(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html");
    Boolean localBoolean2 = Boolean.valueOf(true);
    c = ga.a(1, "gads:sdk_core_location:client:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");
    d = ga.a(1, "gads:active_view_location:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");
    e = ga.a(0, "gads:sdk_core_js_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.js");
    f = ga.a(0, "gads:request_builder:singleton_webview", localBoolean1);
    g = ga.a(0, "gads:request_builder:singleton_webview_experiment_id");
    h = ga.a(0, "gads:request_builder:refresh_if_destroyed:experiment_id");
    i = ga.a(0, "gads:request_builder:refresh_if_destroyed:enable", localBoolean2);
    j = ga.a(0, "gads:sdk_use_dynamic_module", localBoolean2);
    k = ga.a(0, "gads:sdk_use_dynamic_module_experiment_id");
    l = ga.a(0, "gads:sdk_crash_report_enabled", localBoolean1);
    m = ga.a(0, "gads:report_dynamite_crash_in_background_thread", localBoolean1);
    n = ga.a(0, "gads:sdk_crash_report_full_stacktrace", localBoolean1);
    o = ga.a(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    p = ga.a(1, "gads:trapped_exception_sample_rate", 0.01F);
    q = ga.a(0, "gads:block_autoclicks_experiment_id");
    r = ga.a(0, "gads:spam_app_context:experiment_id");
    s = ga.a(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    t = ga.a(1, "gads:video_exo_player:version", "3");
    u = ga.a(1, "gads:video_exo_player:connect_timeout", 8000);
    v = ga.a(1, "gads:video_exo_player:read_timeout", 8000);
    w = ga.a(1, "gads:video_exo_player:loading_check_interval", 1048576);
    x = ga.a(1, "gads:video_exo_player:exo_player_precache_limit", Integer.MAX_VALUE);
    y = ga.a(1, "gads:video_exo_player:byte_buffer_precache_limit", Integer.MAX_VALUE);
    z = ga.a(1, "gads:video_exo_player_socket_receive_buffer_size", 0);
    A = ga.a(0, "gads:video_stream_cache:experiment_id");
    B = ga.a(1, "gads:video_stream_cache:limit_count", 5);
    C = ga.a(1, "gads:video_stream_cache:limit_space", 8388608);
    D = ga.a(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    E = ga.a(1, "gads:video_stream_cache:limit_time_sec", 300L);
    F = ga.a(1, "gads:video_stream_cache:notify_interval_millis", 125L);
    G = ga.a(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    H = ga.a(0, "gads:video:metric_reporting_enabled", localBoolean1);
    I = ga.a(1, "gads:video:metric_frame_hash_times", "");
    J = ga.a(1, "gads:video:metric_frame_hash_time_leniency", 500L);
    K = ga.a(1, "gads:video:force_watermark", localBoolean1);
    L = ga.a(1, "gads:video:surface_update_min_spacing_ms", 1000L);
    M = ga.a(1, "gads:video:spinner:enabled", localBoolean1);
    N = ga.a(1, "gads:video:spinner:scale", 4);
    O = ga.a(1, "gads:video:spinner:jank_threshold_ms", 50L);
    P = ga.a(1, "gads:video:aggressive_media_codec_release", localBoolean1);
    Q = ga.a(1, "gads:memory_bundle:debug_info", localBoolean1);
    R = ga.a(1, "gads:video:codec_query_mime_types", "");
    S = ga.a(1, "gads:video:codec_query_minimum_version", 16);
    T = ga.a(0, "gads:ad_id_app_context:ping_ratio", 0.0F);
    U = ga.a(0, "gads:ad_id_use_shared_preference:experiment_id");
    V = ga.a(0, "gads:ad_id_use_shared_preference:enabled", localBoolean1);
    W = ga.a(0, "gads:ad_id_use_shared_preference:ping_ratio", 0.0F);
    X = ga.a(0, "gads:ad_id_use_persistent_service:enabled", localBoolean1);
    Y = ga.a(0, "gads:ad_id:use_ipc:enabled", localBoolean1);
    Z = ga.a(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    aa = ga.a(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    ba = ga.a(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    ca = ga.a(1, "gad:mraid:version", "2.0");
    da = ga.a(1, "gads:mraid:unload", localBoolean1);
    ea = ga.a(0, "gads:enabled_sdk_csi", localBoolean1);
    fa = ga.a(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    ga = ga.a(0, "gads:sdk_csi_write_to_file", localBoolean1);
    ha = ga.a(0, "gads:enable_content_fetching", localBoolean2);
    ia = ga.a(0, "gads:content_length_weight", 1);
    ja = ga.a(0, "gads:content_age_weight", 1);
    ka = ga.a(0, "gads:min_content_len", 11);
    la = ga.a(0, "gads:fingerprint_number", 10);
    ma = ga.a(0, "gads:sleep_sec", 10);
    na = ga.a(1, "gads:content_vertical_fingerprint_number", 100);
    oa = ga.a(1, "gads:content_vertical_fingerprint_bits", 23);
    pa = ga.a(1, "gads:content_vertical_fingerprint_ngram", 3);
    qa = ga.a(1, "gads:content_fetch_view_tag_id", "googlebot");
    ra = ga.a(1, "gads:content_fetch_exclude_view_tag", "none");
    sa = ga.a(1, "gads:content_fetch_disable_get_title_from_webview", localBoolean1);
    ta = ga.a(0, "gads:app_index:without_content_info_present:enabled", localBoolean2);
    ua = ga.a(0, "gads:app_index:timeout_ms", 1000L);
    va = ga.a(0, "gads:app_index:experiment_id");
    wa = ga.a(1, "gads:content_fetch_enable_new_content_score", localBoolean1);
    xa = ga.a(1, "gads:content_fetch_enable_serve_once", localBoolean1);
    ya = ga.a(0, "gads:ad_key_enabled", localBoolean1);
    za = ga.a(1, "gads:sai:enabled", localBoolean2);
    Aa = ga.a(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    Ba = ga.a(1, "gads:sai:impression_ping_schema_v2", "^[^?]*/adview.*");
    Ca = ga.a(1, "gads:sai:using_macro:enabled", localBoolean1);
    Da = ga.a(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    Ea = ga.a(1, "gads:sai:timeout_ms", -1L);
    Fa = ga.a(1, "gads:sai:scion_thread_pool_size", 5);
    Ga = ga.a(1, "gads:sai:app_measurement_enabled2", localBoolean1);
    Ha = ga.a(2, "app_measurement_enabled", localBoolean1);
    Ia = ga.a(1, "gads:sai:force_through_reflection", localBoolean2);
    Ja = ga.a(1, "gads:sai:gmscore_availability_check_disabled", localBoolean1);
    Ka = ga.a(1, "gads:sai:logging_disabled_for_drx", localBoolean1);
    La = ga.a(1, "gads:interstitial:app_must_be_foreground:enabled", localBoolean1);
    Ma = ga.a(1, "gads:interstitial:foreground_report:enabled", localBoolean1);
    Na = ga.a(0, "gads:webview_cache_version", 0);
    Oa = ga.a(0, "gads:corewebview:experiment_id");
    Pa = ga.a(0, "gads:corewebview:adwebview_factory:enable", localBoolean1);
    Qa = ga.a(0, "gads:corewebview:javascript_engine", localBoolean1);
    Ra = ga.a(1, "gad:webview:inject_scripts", localBoolean1);
    Sa = ga.a(0, "gads:webview:permission:disabled", localBoolean1);
    Ta = ga.a(1, "gads:webview:error_web_response:enabled", localBoolean1);
    Ua = ga.a(1, "gads:rsku:webviewgone:kill_process:enabled", localBoolean1);
    Va = ga.a(1, "gads:webviewgone:kill_process:enabled", localBoolean1);
    Wa = ga.a(1, "gads:rsku:webviewgone:new_onshow:enabled", localBoolean2);
    Xa = ga.a(1, "gads:webviewgone:new_onshow:enabled", localBoolean1);
    Ya = ga.b(0, "gads:pan:experiment_id");
    Za = ga.a(1, "gads:new_rewarded_ad:enabled", localBoolean2);
    _a = ga.a(1, "gads:rewarded:adapter_initialization_enabled", localBoolean1);
    ab = ga.a(1, "gads:rewarded:adapter_timeout_ms", 20000L);
    bb = ga.a(1, "gads:rewarded:ad_metadata_enabled", localBoolean1);
    cb = ga.a(1, "gads:rewarded:ssv_custom_data_enabled", localBoolean2);
    db = ga.a(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500L);
    eb = ga.a(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5L));
    fb = ga.a(1, "gads:adid_values_in_adrequest:enabled", localBoolean1);
    gb = ga.a(1, "gads:adid_values_in_adrequest:timeout", 2000L);
    hb = ga.a(1, "gads:disable_adid_values_in_ms", localBoolean1);
    ib = ga.a(0, "gads:ad_serving:enabled", localBoolean2);
    jb = ga.a(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000L);
    kb = ga.a(1, "gads:custom_close_blocking:enabled", localBoolean1);
    lb = ga.a(1, "gads:disabling_closable_area:enabled", localBoolean1);
    mb = ga.a(1, "gads:use_system_ui_for_fullscreen:enabled", localBoolean1);
    nb = ga.a(1, "gads:ad_overlay:collect_cutout_info:enabled", localBoolean1);
    ob = ga.a(1, "gads:impression_optimization_enabled", localBoolean1);
    pb = ga.a(1, "gads:banner_ad_pool:schema", "customTargeting");
    qb = ga.a(1, "gads:banner_ad_pool:max_queues", 3);
    rb = ga.a(1, "gads:banner_ad_pool:max_pools", 3);
    sb = ga.a(1, "gads:delay_banner_renderer:enabled", localBoolean2);
    tb = ga.a(1, "gads:interstitial_ad_pool:enabled", localBoolean1);
    ub = ga.a(1, "gads:interstitial_ad_pool:enabled_for_rewarded", localBoolean1);
    vb = ga.a(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    wb = ga.a(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    xb = ga.a(1, "gads:interstitial_ad_pool:max_pools", 3);
    yb = ga.a(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    zb = ga.a(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    Ab = ga.a(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    Bb = ga.a(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    Cb = ga.a(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    Db = ga.a(1, "gads:interstitial_ad_pool:discard_thresholds", 0L);
    Eb = ga.a(1, "gads:interstitial_ad_pool:miss_thresholds", 0L);
    Fb = ga.a(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0F);
    Gb = ga.a(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0F);
    Hb = ga.a(0, "gads:debug_logging_feature:enable", localBoolean1);
    Ib = ga.a(0, "gads:debug_logging_feature:intercept_web_view", localBoolean1);
    Jb = ga.a(1, "gads:heap_wastage:bytes", 0);
    Kb = ga.a(1, "gads:spherical_video:vertex_shader", "");
    Lb = ga.a(1, "gads:spherical_video:fragment_shader", "");
    Mb = ga.a(0, "gads:log:verbose_enabled", localBoolean1);
    Nb = ga.a(1, "gads:include_local_global_rectangles", localBoolean1);
    Ob = ga.a(1, "gads:position_watcher:throttle_ms", 200L);
    Pb = ga.a(1, "gads:position_watcher:scroll_aware_throttle_ms", 33L);
    Qb = ga.a(1, "gads:position_watcher:enable_scroll_aware_ads", localBoolean1);
    Rb = ga.a(1, "gads:position_watcher:send_scroll_data", localBoolean1);
    Sb = ga.a(0, "gads:device_info_caching_expiry_ms:expiry", 300000L);
    Tb = ga.a(1, "gads:gen204_signals:enabled", localBoolean1);
    Ub = ga.a(0, "gads:webview:error_reporting_enabled", localBoolean1);
    Vb = ga.a(0, "gads:adid_reporting:enabled", localBoolean1);
    Wb = ga.a(0, "gads:ad_settings_page_reporting:enabled", localBoolean1);
    Xb = ga.a(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", localBoolean1);
    Yb = ga.a(1, "gads:rtb_signal_timeout_ms", 1000L);
    Zb = ga.a(2, "rtb_enabled", localBoolean1);
    _b = ga.a(1, "gads:rtb_cld:enabled", localBoolean1);
    ac = ga.a(0, "gads:resolve_future:default_timeout_ms", 30000L);
    bc = ga.a(0, "gads:ad_loader:timeout_ms", 60000L);
    cc = ga.a(0, "gads:rendering:timeout_ms", 60000L);
    dc = ga.a(1, "gads:adapter_initialization:enabled", localBoolean1);
    ec = ga.a(1, "gads:adapter_initialization:timeout", 30L);
    fc = ga.a(1, "gads:adapter_initialization:cld_timeout", 10L);
    gc = ga.a(0, "gads:adshield:enable_adshield_instrumentation", localBoolean1);
    hc = ga.a(1, "gads:gestures:errorlogging:enabled", localBoolean1);
    ic = ga.a(1, "gads:gestures:task_timeout", 2000L);
    jc = ga.a(1, "gads:gestures:asig:enabled", localBoolean1);
    kc = ga.a(1, "gads:gestures:ans:enabled", localBoolean1);
    lc = ga.a(1, "gads:gestures:tos:enabled", localBoolean1);
    mc = ga.a(1, "gads:gestures:brt:enabled", localBoolean2);
    nc = ga.a(1, "gads:signal:app_permissions:disabled", localBoolean1);
    oc = ga.a(1, "gads:gestures:inthex:enabled", localBoolean1);
    pc = ga.a(1, "gads:gestures:hpk:enabled", localBoolean2);
    qc = ga.a(1, "gads:gestures:pk", "");
    rc = ga.a(1, "gads:gestures:bs:enabled", localBoolean2);
    sc = ga.a(1, "gads:gestures:check_initialization_thread:enabled", localBoolean1);
    tc = ga.a(1, "gads:gestures:get_query_in_non_ui_thread:enabled", localBoolean2);
    uc = ga.a(1, "gads:gestures:pds:enabled", localBoolean1);
    vc = ga.a(1, "gads:gestures:ns:enabled", localBoolean1);
    wc = ga.a(1, "gads:gestures:vdd:enabled", localBoolean1);
    xc = ga.a(0, "gads:adid_notification:first_party_check:enabled", localBoolean2);
    yc = ga.a(0, "gads:adid_track_reset_count:enabled", localBoolean2);
    zc = ga.a(1, "gads:sdk_core_constants:experiment_id");
    Ac = ga.a(1, "gads:sdk_core_constants:caps", "");
    Bc = ga.a(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12L));
    Cc = ga.a(0, "gads:js_flags:mf", localBoolean1);
    Dc = ga.a(1, "gads:js_flags:disable_phenotype", localBoolean1);
    Ec = ga.a(0, "gads:custom_render:ping_on_ad_rendered", localBoolean1);
    Fc = ga.a(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    Gc = ga.a(0, "gads:native:engine_js_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/native_ads.js");
    Hc = ga.a(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
    Ic = ga.a(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    Jc = ga.a(1, "gads:native_video_load_timeout", 10);
    Kc = ga.a(1, "gads:omid:native_webview_load_timeout", 2000);
    Lc = ga.a(1, "gads:enable_native_media_aspect_ratio", localBoolean2);
    Mc = ga.a(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    Nc = ga.a(1, "gads:enable_store_active_view_state", localBoolean1);
    Oc = ga.a(1, "gads:enable_singleton_broadcast_receiver", localBoolean1);
    Pc = ga.a(1, "gads:native:media_view_match_parent:enabled", localBoolean1);
    Qc = ga.a(1, "gads:native:count_impression_for_assets", localBoolean1);
    Rc = ga.a(1, "gads:instream_ad:enabled", localBoolean2);
    Sc = ga.a(1, "gads:fluid_ad:use_wrap_content_height", localBoolean1);
    Tc = ga.a(1, "gads:auto_location_for_coarse_permission", localBoolean1);
    Uc = ga.b(1, "gads:auto_location_for_coarse_permission:experiment_id");
    Vc = ga.a(1, "gads:auto_location_timeout", 2000L);
    Wc = ga.b(1, "gads:auto_location_timeout:experiment_id");
    Xc = ga.a(1, "gads:auto_location_interval", -1L);
    Yc = ga.b(1, "gads:auto_location_interval:experiment_id");
    Zc = ga.a(0, "gads:auto_location_interval:without_thread", localBoolean2);
    _c = ga.a(1, "gads:fetch_app_settings_using_cld:enabled", localBoolean1);
    ad = ga.a(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    bd = ga.a(1, "gads:use_manifest_appid_cld:enabled", localBoolean1);
    cd = ga.a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000L);
    dd = ga.a(0, "gads:afs:csa:experiment_id");
    ed = ga.a(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    fd = ga.a(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    gd = ga.a(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    hd = ga.a(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    id = ga.a(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    jd = ga.a(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000L);
    kd = ga.a(1, "gads:parental_controls:timeout", 2000L);
    ld = ga.a(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    md = ga.a(0, "gads:safe_browsing:safety_net:delay_ms", 2000L);
    nd = ga.a(0, "gads:safe_browsing:debug", localBoolean1);
    od = ga.a(1, "gads:cache:ad_request_timeout_millis", 250);
    pd = ga.a(1, "gads:cache:max_concurrent_downloads", 10);
    qd = ga.a(1, "gads:cache:javascript_timeout_millis", 5000L);
    rd = ga.a(1, "gads:cache:bind_on_foreground", localBoolean1);
    sd = ga.a(1, "gads:cache:bind_on_init", localBoolean1);
    td = ga.a(1, "gads:cache:bind_on_request", localBoolean1);
    ud = ga.a(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30L));
    vd = ga.a(1, "gads:cache:use_cache_data_source", localBoolean1);
    wd = ga.a(1, "gads:cache:connection_per_read", localBoolean1);
    xd = ga.a(1, "gads:cache:connection_timeout", 5000L);
    yd = ga.a(1, "gads:cache:read_only_connection_timeout", 5000L);
    zd = ga.a(1, "gads:http_assets_cache:enabled", localBoolean1);
    Ad = ga.a(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    Bd = ga.a(1, "gads:http_assets_cache:time_out", 100);
    Cd = ga.a(1, "gads:chrome_custom_tabs_browser:enabled", localBoolean1);
    Dd = ga.a(1, "gads:chrome_custom_tabs:disabled", localBoolean1);
    Ed = ga.a(1, "gads:debug_hold_gesture:time_millis", 2000L);
    Fd = ga.a(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    Gd = ga.a(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    Hd = ga.a(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    Id = ga.a(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    Jd = ga.a(1, "gads:drx_debug:timeout_ms", 5000);
    Kd = ga.a(1, "gad:pixel_dp_comparision_multiplier", 1);
    Ld = ga.a(1, "gad:interstitial_for_multi_window", localBoolean1);
    Md = ga.a(1, "gad:interstitial_ad_stay_active_in_multi_window", localBoolean1);
    Nd = ga.a(1, "gad:interstitial_multi_window_method", localBoolean1);
    Od = ga.a(1, "gad:interstitial:close_button_padding_dip", 0);
    Pd = ga.a(1, "gads:clearcut_logging:enabled", localBoolean1);
    Qd = ga.a(1, "gads:clearcut_logging:write_to_file", localBoolean1);
    Rd = ga.a(0, "gad:force_local_ad_request_service:enabled", localBoolean1);
    Sd = ga.a(1, "gad:publisher_testing:force_local_request:enabled", localBoolean2);
    Td = ga.a(1, "gad:publisher_testing:force_local_request:enabled_list", "");
    Ud = ga.a(1, "gad:publisher_testing:force_local_request:disabled_list", "");
    Vd = ga.a(0, "gad:force_dynamite_loading_enabled", localBoolean1);
    Wd = ga.a(0, "gad:dynamite_module:experiment_id");
    Xd = ga.a(1, "gad:http_redirect_max_count:times", 8);
    Yd = ga.a(1, "gads:omid:enabled", localBoolean1);
    Zd = ga.a(1, "gads:omid:destroy_webview_delay", 1000);
    _d = ga.a(0, "gads:nonagon:red_button", localBoolean1);
    ae = ga.a(1, "gads:nonagon:banner:enabled", localBoolean1);
    be = ga.a(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    ce = ga.a(1, "gads:nonagon:interstitial:enabled", localBoolean1);
    de = ga.a(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    ee = ga.a(1, "gads:nonagon:rewardedvideo:enabled", localBoolean1);
    fe = ga.a(1, "gads:nonagon:mobile_ads_setting_manager:enabled", localBoolean1);
    ge = ga.a(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    he = ga.a(1, "gads:nonagon:nativead:enabled", localBoolean1);
    ie = ga.a(1, "gads:nonagon:nativead:app_name", "(?!)");
    je = ga.a(1, "gads:nonagon:banner:check_dp_size", localBoolean1);
    ke = ga.a(1, "gads:nonagon:rewarded:load_multiple_ads", localBoolean2);
    le = ga.a(1, "gads:nonagon:return_last_error_code", localBoolean1);
    me = ga.a(1, "gads:nonagon:return_no_fill_error_code", localBoolean1);
    ne = ga.a(1, "gads:nonagon:continue_on_no_fill", localBoolean1);
    oe = ga.a(1, "gads:nonagon:open_not_loaded_interstitial", localBoolean2);
    pe = ga.a(1, "gads:nonagon:separate_timeout:enabled", localBoolean1);
    qe = ga.a(1, "gads:nonagon:request_timeout:seconds", 60);
    re = ga.a(0, "gads:nonagon:limit_ad_request_connection", localBoolean2);
    se = ga.a(1, "gads:nonagon:javascript_ad_request:enabled", localBoolean1);
    te = ga.a(1, "gads:nonagon:banner_recursive_renderer", localBoolean1);
    ue = ga.a(1, "gads:nonagon:service:enabled", localBoolean2);
    ve = ga.a(1, "gads:signals:ad_id_info:enabled", localBoolean1);
    we = ga.a(1, "gads:signals:app_index:enabled", localBoolean1);
    xe = ga.a(1, "gads:signals:cache:enabled", localBoolean1);
    ye = ga.a(1, "gads:signals:doritos:enabled", localBoolean1);
    ze = ga.a(1, "gads:signals:doritos:v1:enabled", localBoolean1);
    Ae = ga.a(1, "gads:signals:doritos:v2:immediate:enabled", localBoolean1);
    Be = ga.a(1, "gads:signals:location:enabled", localBoolean1);
    Ce = ga.a(1, "gads:signals:network_prediction:enabled", localBoolean1);
    De = ga.a(1, "gads:signals:parental_control:enabled", localBoolean1);
    Ee = ga.a(1, "gads:signals:video_decoder:enabled", localBoolean1);
    Fe = ga.a(1, "gads:signals:signals_on_service:enabled", localBoolean1);
    Ge = ga.a(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000L);
    He = ga.a(0, "gads:public_beta:traffic_multiplier", "1.0");
    Ie = ga.a(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);
    Je = ga.a(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", 999);
    Ke = ga.a(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 26);
    Le = ga.a(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 27);
    Me = ga.a(0, "gads:rewarded_sku:enabled", localBoolean2);
    Ne = ga.a(0, "gads:rewarded_sku:override_test:enabled", localBoolean1);
    Oe = ga.a(1, "gads:consent:shared_preference_reading:enabled", localBoolean2);
    Pe = ga.a(1, "gads:consent:iab_consent_info:enabled", localBoolean2);
    Qe = ga.a(1, "gads:nativeads:image:sample:enabled", localBoolean2);
    Re = ga.a(1, "gads:nativeads:image:sample:pixels", 1048576);
    Se = ga.a(1, "gads:nativeads:overlay_webview:onclick", localBoolean1);
    Te = ga.a(0, "gads:dynamite_load:fail:sample_rate", 10000);
    Ue = ga.a(0, "gads:service:webview:enable_directory_suffix", localBoolean2);
    Ve = ga.a(1, "gads:offline_signaling:enabled", localBoolean1);
    We = ga.a(1, "gads:offline_signaling:log_maximum", 100);
    Xe = ga.a(0, "gads:uri_query_to_map_rewrite:enabled", localBoolean1);
    Ye = ga.a(1, "gads:nativeads:template_signal:enabled", localBoolean2);
    Ze = ga.a(1, "gads:nativeads:media_content_aspect_ratio:enabled", localBoolean2);
  }
  
  public static List<String> a()
  {
    return Kea.d().a();
  }
  
  public static void a(Context paramContext)
  {
    zl.a(paramContext, new sa(paramContext));
    paramContext = Jb;
    int i1 = ((Integer)Kea.e().a(paramContext)).intValue();
    if ((i1 > 0) && (_e == null)) {
      _e = new byte[i1];
    }
  }
  
  public static void a(Context paramContext, int paramInt, JSONObject paramJSONObject)
  {
    Kea.c();
    paramContext = paramContext.getSharedPreferences("google_ads_flags", 0).edit();
    Kea.d().a(paramContext, 1, paramJSONObject);
    Kea.c();
    paramContext.commit();
  }
  
  public static List<String> b()
  {
    return Kea.d().b();
  }
}


/* Location:              /Applications/dex2jar/classes-dex2jar.jar!/com/google/android/gms/internal/ads/ra.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */